Repository Team-GONG-BAEK/gong-baek-android, pull requests merged in 2025-05, with the labels that each got.

#46 [Refactor/45] "회원가입 - 학교/학과 검색" 엠티뷰를 추가합니다.
  app/src/main/java/com/sopt/gongbaek/domain/usecase/SearchMajorsUseCase.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/component/SearchResultSection.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/AuthViewModel.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/MajorSearchScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/UnivSearchScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/state/AcademicInfoState.kt
Labels: ♻️ Refactor, 🐶 대현

#48 [Feat/44] "채우기 뷰 - 로딩 뷰"를 추가합니다.
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/stateView/LoadingScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/stateView/LoadingViewAnimation.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouplist/screen/GroupListScreen.kt
  app/src/main/res/values/strings.xml
Labels: ✨ Feat, ❤️‍🔥 민서

#56 [Chore] "모임 생성" UI 변경사항을 반영합니다.
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupPlacePeopleScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupRegisterScreen.kt
  app/src/main/res/values/strings.xml
Labels: ❤️‍🩹 Chore, ❤️‍🔥 민서

#54 [Fix/51] 뒤로가기가 중복발생하는 문제를 해결합니다.
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/navigation/AuthNavGraph.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupdetail/navigation/GroupDetailNavGraph.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/navigation/GroupRegisterNavGraph.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouproom/navigation/GroupRoomNavGraph.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/main/MainNavHost.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/main/MainNavigator.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mypage/navigation/MyPageNavGraph.kt
Labels: 🛠️ Fix, 🐶 대현

#57 [Feat/53] 릴리즈 전 최종 QA 대비 보완사항을 해결합니다.
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/tabpager/CustomTabPager.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupdetail/screen/GroupDetailScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/login/SocialLoginScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/onboarding/screen/TermsOfServiceContract.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/onboarding/screen/TermsOfServiceScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/splash/SplashScreen.kt
Labels: ✨ Feat, 🌱 민재

#60 [Feat/59] 모임상세 뷰 잔여 기능을 구현합니다.
  app/src/main/java/com/sopt/gongbaek/data/remote/datasource/CommentRemoteDataSource.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/datasource/GroupRemoteDataSource.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/datasourceimpl/CommentRemoteDataSourceImpl.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/datasourceimpl/GroupRemoteDataSourceImpl.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/dto/request/DeleteCommentRequestDto.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/dto/request/GroupManagementRequestDto.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/service/CommentService.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/service/GroupService.kt
  app/src/main/java/com/sopt/gongbaek/data/repositoryimpl/CommentRepositoryImpl.kt
  app/src/main/java/com/sopt/gongbaek/data/repositoryimpl/GroupRepositoryImpl.kt
  app/src/main/java/com/sopt/gongbaek/di/UseCaseModule.kt
  app/src/main/java/com/sopt/gongbaek/domain/repository/CommentRepository.kt
  app/src/main/java/com/sopt/gongbaek/domain/repository/GroupRepository.kt
  app/src/main/java/com/sopt/gongbaek/domain/usecase/CancelGroupUseCase.kt
  app/src/main/java/com/sopt/gongbaek/domain/usecase/DeleteCommentUseCase.kt
  app/src/main/java/com/sopt/gongbaek/domain/usecase/DeleteGroupUseCase.kt
  app/src/main/java/com/sopt/gongbaek/presentation/type/GongBaekDialogType.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/dialog/GongBaekDialog.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/section/CommentSection.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/stateView/ErrorScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupdetail/navigation/GroupDetailNavGraph.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupdetail/screen/GroupDetailContract.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupdetail/screen/GroupDetailInfoSection.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupdetail/screen/GroupDetailScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupdetail/screen/GroupDetailViewModel.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouproom/screen/GroupRoomContract.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouproom/screen/GroupRoomScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouproom/screen/GroupRoomViewModel.kt
  app/src/main/res/values/strings.xml
Labels: ✨ Feat, 🌱 민재

#61 [Feat/43] "에러대응" 화면을 추가합니다.
  app/src/main/java/com/sopt/gongbaek/data/remote/datasource/GroupRemoteDataSource.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/datasourceimpl/GroupRemoteDataSourceImpl.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/service/GroupService.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/util/AuthInterceptor.kt
  app/src/main/java/com/sopt/gongbaek/data/repositoryimpl/GroupRepositoryImpl.kt
  app/src/main/java/com/sopt/gongbaek/domain/repository/GroupRepository.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/stateView/ErrorScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/stateView/LoadingScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/stateView/LoadingViewAnimation.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouplist/screen/GroupListScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouplist/screen/GroupListViewModel.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/home/component/section/NearestGroupSection.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/home/screen/HomeContract.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/home/screen/HomeScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/home/screen/HomeViewModel.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mypage/screen/MyPageScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mypage/screen/MyPageViewModel.kt
  app/src/main/java/com/sopt/gongbaek/presentation/util/NearestGroupFormatSchedule.kt
  app/src/main/res/values/strings.xml
Labels: ✨ Feat, 🐶 대현

#65 [Refactor/63] 담당 뷰 자체 QA 사항을 반영합니다. (대현)
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/AuthContract.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/AuthViewModel.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/EmailVerificationScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/EnterTimeTableScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/MbtiScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/NicknameGenderScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/SelectProfileScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/SelfIntroductionScreen.kt
Labels: ♻️ Refactor, 🐶 대현

#64 [Refactor/58] 자체 QA 수정사항을 반영합니다.
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupRegisterScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupRegisterViewModel.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mypage/screen/MyPageViewModel.kt
Labels: ♻️ Refactor, ❤️‍🔥 민서

#68 [Refactor/67] 1차 QA 수정사항을 반영합니다. (민서)
  app/src/main/java/com/sopt/gongbaek/presentation/type/SelectableButtonType.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/button/GongBaekSelectableButton.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/button/ImageSelector.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/section/GroupInfoSection.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/component/GroupCategorySelectableButton.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupIntroductionScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/util/FormatGroupTimeDescription.kt
  app/src/main/res/values/strings.xml
Labels: ♻️ Refactor, ❤️‍🔥 민서

#69 [Refactor/62] 1차 QA 수정사항을 반영합니다. (민재)
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupdetail/screen/GroupDetailScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouproom/screen/GroupRoomScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/onboarding/navigation/OnboardingNavGraph.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/onboarding/screen/OnboardingScreen.kt
Labels: ♻️ Refactor, 🌱 민재

#73 [Refactor/70] 에러대응 방식을 개선합니다.
  app/src/main/java/com/sopt/gongbaek/data/remote/util/ApiResponseException.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/util/ApiResponseHandler.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/util/HttpResponseException.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/util/HttpResponseHandler.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/util/SafeApiCall.kt
  app/src/main/java/com/sopt/gongbaek/data/repositoryimpl/AuthRepositoryImpl.kt
  app/src/main/java/com/sopt/gongbaek/data/repositoryimpl/CommentRepositoryImpl.kt
  app/src/main/java/com/sopt/gongbaek/data/repositoryimpl/GroupRepositoryImpl.kt
  app/src/main/java/com/sopt/gongbaek/data/repositoryimpl/SearchRepositoryImpl.kt
  app/src/main/java/com/sopt/gongbaek/data/repositoryimpl/TokenRepositoryImpl.kt
  app/src/main/java/com/sopt/gongbaek/data/repositoryimpl/UserRepositoryImpl.kt
Labels: ♻️ Refactor, 🌱 민재

#76 [Feat/74] 모임 신청 시, 인원 마감에 대한 에러 대응을 추가합니다.
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupdetail/screen/GroupDetailContract.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupdetail/screen/GroupDetailScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupdetail/screen/GroupDetailViewModel.kt
Labels: ✨ Feat, 🌱 민재

#78 [Feat/77] 모임상세, 스페이스에서 탈퇴자에 대한 대응을 구현합니다.
  app/src/main/java/com/sopt/gongbaek/data/remote/dto/response/GroupCommentsResponseDto.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/dto/response/GroupMembersResponseDto.kt
  app/src/main/java/com/sopt/gongbaek/domain/model/GroupComments.kt
  app/src/main/java/com/sopt/gongbaek/domain/model/GroupHost.kt
  app/src/main/java/com/sopt/gongbaek/domain/model/GroupMembers.kt
  app/src/main/java/com/sopt/gongbaek/domain/usecase/LoadGroupDetailScreenUseCase.kt
  app/src/main/java/com/sopt/gongbaek/domain/usecase/LoadGroupRoomScreenUseCase.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/section/CommentSection.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupdetail/screen/GroupDetailInfoSection.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouproom/screen/GroupRoomScreen.kt
  app/src/main/res/values/strings.xml
Labels: ✨ Feat, 🌱 민재

#79 [Refactor/75] 담당 컴포넌트(시간표, 피커) 로직을 리펙토링 합니다.
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/component/YearSelectableButton.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/component/YearSelectionBottomSheet.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/AuthViewModel.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/picker/Picker.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/timetable/GroupRegisterTimeTable.kt
Labels: ♻️ Refactor, 🐶 대현
