Repository Team-GONG-BAEK/gong-baek-android, pull requests merged in 2025-03, with the labels that each got.

#9 [Refactor/8] "회원가입" flow를 변경합니다.
  app/src/main/java/com/sopt/gongbaek/presentation/model/AuthNavGraphRoute.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/navigation/AuthNavGraph.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/navigation/AuthNavigator.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/AcademicInfoScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/AuthContract.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/AuthViewModel.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/EmailVerificationScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/EnterTimeTableScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/MbtiScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/NicknameGenderScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/SelectProfileScreen.kt
  app/src/main/res/values/strings.xml
Labels: ✨ Feat, ♻️ Refactor, 🐶 대현

#10 [Feat/6] "마이페이지 - 메인" 뷰를 구현합니다.
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/topbar/CenterTitleTopBar.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupdetail/screen/GroupDetailContract.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mygroup/navigation/MyGroupNavGraph.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mygroup/navigation/MyGroupNavigator.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mygroup/screen/MyGroupScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mypage/component/MyGroupScreenContent.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mypage/navigation/MyPageNavGraph.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mypage/screen/MyPageContract.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mypage/screen/MyPageScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mypage/screen/MyPageViewModel.kt
  app/src/main/res/drawable/ic_setting_48.xml
  app/src/main/res/values/strings.xml
Labels: ⛔️ Del, ✨ Feat, ❤️‍🔥 민서

#11 [Feat/3] 카카오로그인을 구현합니다.
  .github/workflows/main.yml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/gongbaek/GongBaekApp.kt
  app/src/main/java/com/sopt/gongbaek/data/local/datasource/TokenLocalDataSource.kt
  app/src/main/java/com/sopt/gongbaek/data/local/datasourceimpl/TokenLocalDataSourceImpl.kt
  app/src/main/java/com/sopt/gongbaek/data/mapper/todomain/LoginResponseDtoMapper.kt
  app/src/main/java/com/sopt/gongbaek/data/mapper/todomain/RegisterUserInfoResponseDtoMapper.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/datasource/AuthRemoteDataSource.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/datasourceimpl/AuthRemoteDatasourceImpl.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/dto/request/LoginRequestDto.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/dto/response/LoginResponseDto.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/service/AuthService.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/util/AuthInterceptor.kt
  app/src/main/java/com/sopt/gongbaek/data/repositoryimpl/AuthRepositoryImpl.kt
  app/src/main/java/com/sopt/gongbaek/data/repositoryimpl/TokenRepositoryImpl.kt
  app/src/main/java/com/sopt/gongbaek/di/NetworkModule.kt
  app/src/main/java/com/sopt/gongbaek/di/UseCaseModule.kt
  app/src/main/java/com/sopt/gongbaek/domain/model/UserAuth.kt
  app/src/main/java/com/sopt/gongbaek/domain/repository/AuthRepository.kt
  app/src/main/java/com/sopt/gongbaek/domain/repository/TokenRepository.kt
  app/src/main/java/com/sopt/gongbaek/domain/usecase/LoginUseCase.kt
  app/src/main/java/com/sopt/gongbaek/domain/usecase/LogoutUseCase.kt
  app/src/main/java/com/sopt/gongbaek/domain/usecase/ReissueTokenUseCase.kt
  app/src/main/java/com/sopt/gongbaek/presentation/model/NavigationRoute.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/login/SocialLoginContract.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/login/SocialLoginScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/login/SocialLoginViewModel.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/main/MainBottomNavBar.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/main/MainNavHost.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/onboarding/screen/TermsOfServiceContract.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/onboarding/screen/TermsOfServiceScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/onboarding/screen/TermsOfServiceViewModel.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/splash/SplashContract.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/splash/SplashScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/splash/SplashViewModel.kt
  app/src/main/res/drawable/ic_check_fill.xml
  app/src/main/res/drawable/ic_check_unfill.xml
  app/src/main/res/drawable/ic_radio_btn_fill.xml
  app/src/main/res/drawable/ic_radio_btn_unfill.xml
  app/src/main/res/drawable/img_kakao_login_btn.png
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: ✨ Feat, 🌱 민재
