Repository Team-GONG-BAEK/gong-baek-android, pull requests merged in 2025-04, with the labels that each got.

#15 [Feat/14] "마이페이지 메인 뷰" 로직 구현, API를 연결합니다.
  app/src/main/java/com/sopt/gongbaek/data/mapper/todomain/MyProfileResponseDtoMapper.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/datasource/UserRemoteDataSource.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/datasourceimpl/UserRemoteDataSourceImpl.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/dto/response/MyProfileResponseDto.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/service/UserService.kt
  app/src/main/java/com/sopt/gongbaek/data/repositoryimpl/UserRepositoryImpl.kt
  app/src/main/java/com/sopt/gongbaek/di/DataSourceModule.kt
  app/src/main/java/com/sopt/gongbaek/di/RepositoryModule.kt
  app/src/main/java/com/sopt/gongbaek/di/ServiceModule.kt
  app/src/main/java/com/sopt/gongbaek/di/UseCaseModule.kt
  app/src/main/java/com/sopt/gongbaek/domain/repository/UserRepository.kt
  app/src/main/java/com/sopt/gongbaek/domain/usecase/GetMyProfileUseCase.kt
  app/src/main/java/com/sopt/gongbaek/presentation/model/NavigationRoute.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mypage/navigation/MyPageNavGraph.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mypage/navigation/MyPageNavigator.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mypage/screen/MyPageContract.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mypage/screen/MyPageScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mypage/screen/MyPageViewModel.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mypage/screen/SettingScreen.kt
Labels: ✨ Feat, ❤️‍🔥 민서

#17 [Feat/13] "회원가입" 로직을 구현합니다.
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/navigation/AuthNavGraph.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/AcademicInfoScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/AuthContract.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/AuthViewModel.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/CompleteAuthScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/EmailVerificationScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/EnterTimeTableScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/MajorSearchScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/MbtiScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/NicknameGenderScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/SelectProfileScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/SelfIntroductionScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/UnivSearchScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/state/AcademicInfoState.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/state/EmailVerificationState.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/state/EmailVerificationStep.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/state/EnterTimeTableState.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/state/MbtiState.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/state/NicknameGenderState.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/state/SelectProfileState.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/state/SelfIntroductionState.kt
  app/src/main/java/com/sopt/gongbaek/presentation/util/FormatTimeLeft.kt
  app/src/main/java/com/sopt/gongbaek/presentation/util/extension/CharExt.kt
Labels: ✨ Feat, ♻️ Refactor, 🐶 대현

#19 [Feat/16] "마이페이지 설정 뷰" UI, 로직을 구현합니다.
  app/src/main/java/com/sopt/gongbaek/presentation/type/GongBaekDialogType.kt
  app/src/main/java/com/sopt/gongbaek/presentation/type/GongBaekWebView.kt
  app/src/main/java/com/sopt/gongbaek/presentation/type/SettingServiceGuideItem.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/dialog/AccountDialog.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/dialog/GongBaekDialog.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/main/MainNavHost.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mypage/component/MyGroupScreenContent.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mypage/navigation/MyPageNavGraph.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mypage/screen/MyPageContract.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mypage/screen/MyPageScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mypage/screen/MyPageViewModel.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mypage/screen/SettingScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/util/GongBaekOpenWebView.kt
  app/src/main/res/values/strings.xml
Labels: ✨ Feat, ❤️‍🔥 민서

#26 [Chore/24] "모임 모집하기" UI 변경사항을 반영합니다.
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupCycleScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupIntroductionScreen.kt
  app/src/main/res/values/strings.xml
Labels: ❤️‍🩹 Chore, ❤️‍🔥 민서

#29 [Fix/27] 화면 padding 값을 조정합니다.
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/topbar/CenterTitleTopBar.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/topbar/StartTitleTopBar.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouplist/navigation/GroupListNavGraph.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouplist/screen/GroupListScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupCoverScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupTimeScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/home/navigation/HomeNavGraph.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/home/screen/HomeScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/main/MainBottomNavBar.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/main/MainNavHost.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/main/MainScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mypage/navigation/MyPageNavGraph.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mypage/screen/MyPageScreen.kt
Labels: 🛠️ Fix, 🐶 대현

#28 [Refactor/25] "채우기 뷰" UI 변경사항을 반영합니다.
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/section/GroupInfoSection.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouplist/screen/GroupListScreen.kt
Labels: ♻️ Refactor, ❤️‍🔥 민서

#30 [Feat/21] "홈" 화면 UI 변경사항을 반영합니다.
  app/src/main/java/com/sopt/gongbaek/presentation/type/GongBaekWebView.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/home/component/section/HomeBannerSection.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/home/component/section/MemberRecommendSection.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/home/component/section/NearestGroupSection.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/home/component/section/OnceRecommendSection.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/home/component/section/WeekRecommendSection.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/home/screen/HomeScreen.kt
  app/src/main/res/drawable/img_home_banner.png
  app/src/main/res/drawable/img_home_comingsoon.png
  app/src/main/res/values/strings.xml
Labels: ✨ Feat, 🐶 대현

#31 [Refactor/22] Gradle Scripts를 정리합니다.
  .github/workflows/main.yml
  app/build.gradle.kts
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/BuildProperties.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: ♻️ Refactor, 🌱 민재

#35 [Refactor/34] "모임 모집하기" 모임 시간표 ui를 수정합니다.
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/timetable/GroupRegisterTimeTable.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupTimeScreen.kt
Labels: ♻️ Refactor, 🐶 대현

#40 [Feat/39] "홈" 화면 모임 추천 엠티뷰를 추가합니다.
  app/src/main/java/com/sopt/gongbaek/presentation/ui/home/component/section/EmptyRecommendSection.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/home/component/section/OnceRecommendSection.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/home/component/section/WeekRecommendSection.kt
  app/src/main/res/values/strings.xml
Labels: ✨ Feat, 🐶 대현

#41 [Feat/37] "모임 상세뷰" 추가 기능을 구현합니다.
  app/src/main/java/com/sopt/gongbaek/data/mapper/todomain/GroupHostResponseDtoMapper.kt
  app/src/main/java/com/sopt/gongbaek/data/remote/dto/response/GroupHostResponseDto.kt
  app/src/main/java/com/sopt/gongbaek/domain/model/GroupHost.kt
  app/src/main/java/com/sopt/gongbaek/domain/model/UserInfo.kt
  app/src/main/java/com/sopt/gongbaek/domain/type/GradeType.kt
  app/src/main/java/com/sopt/gongbaek/presentation/type/GongBaekWebView.kt
  app/src/main/java/com/sopt/gongbaek/presentation/type/SelectableButtonType.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/AcademicInfoScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/EmailVerificationScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/EnterTimeTableScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/MbtiScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/NicknameGenderScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/SelectProfileScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/SelfIntroductionScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/button/GongBaekSelectableButton.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/component/topbar/StartTitleTopBar.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupdetail/screen/GroupDetailInfoSection.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupdetail/screen/GroupDetailScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupCategoryScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupCoverScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupCycleScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupIntroductionScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupPlacePeopleScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupRegisterScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/GroupTimeScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/SelectDayOfWeekScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/groupregister/screen/SelectDayScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/grouproom/screen/GroupRoomScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/mypage/screen/SettingScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/onboarding/screen/OnboardingScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/onboarding/screen/TermsOfServiceScreen.kt
  app/src/main/res/drawable/ic_report_48.xml
  app/src/main/res/values/strings.xml
Labels: ✨ Feat, ❤️‍🔥 민서

#42 [Refactor/36] "회원가입" 이메일 인증 예외처리를 수정합니다.
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/AuthViewModel.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/screen/EmailVerificationScreen.kt
  app/src/main/java/com/sopt/gongbaek/presentation/ui/auth/state/EmailVerificationState.kt
Labels: ♻️ Refactor, 🐶 대현
